// Array of country codes and names
const countries = [
    { code: '+1', name: 'United States/Canada', flag: '🇺🇸' },
    { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
    { code: '+91', name: 'India', flag: '🇮🇳' },
    { code: '+61', name: 'Australia', flag: '🇦🇺' },
    { code: '+49', name: 'Germany', flag: '🇩🇪' },
    { code: '+33', name: 'France', flag: '🇫🇷' },
    { code: '+81', name: 'Japan', flag: '🇯🇵' },
    { code: '+86', name: 'China', flag: '🇨🇳' },
    { code: '+7', name: 'Russia', flag: '🇷🇺' },
    { code: '+55', name: 'Brazil', flag: '🇧🇷' },
    { code: '+52', name: 'Mexico', flag: '🇲🇽' },
    { code: '+34', name: 'Spain', flag: '🇪🇸' },
    { code: '+82', name: 'South Korea', flag: '🇰🇷' },
    { code: '+39', name: 'Italy', flag: '🇮🇹' },
    { code: '+31', name: 'Netherlands', flag: '🇳🇱' },
    { code: '+90', name: 'Turkey', flag: '🇹🇷' },
    { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
    { code: '+65', name: 'Singapore', flag: '🇸🇬' },
    { code: '+27', name: 'South Africa', flag: '🇿🇦' },
    { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪' },
    { code: '+20', name: 'Egypt', flag: '🇪🇬' },
    { code: '+92', name: 'Pakistan', flag: '🇵🇰' },
    { code: '+234', name: 'Nigeria', flag: '🇳🇬' },
    { code: '+880', name: 'Bangladesh', flag: '🇧🇩' },
    { code: '+84', name: 'Vietnam', flag: '🇻🇳' },
    { code: '+62', name: 'Indonesia', flag: '🇮🇩' },
    { code: '+63', name: 'Philippines', flag: '🇵🇭' },
    { code: '+60', name: 'Malaysia', flag: '🇲🇾' },
    { code: '+66', name: 'Thailand', flag: '🇹🇭' },
    { code: '+48', name: 'Poland', flag: '🇵🇱' },
  ];
  
  export default countries;